alfresco-mobile-android/src/main/assets/Configuration/Messages/en_embedded_strings.properties
alfresco-mobile-android/src/main/assets/Configuration/Messages/fr_embedded_strings.properties
alfresco-mobile-android/src/main/assets/Configuration/embedded_config.json
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/activity/MainActivity.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/editors/text/TextEditorActivity.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/help/HelpDialogFragment.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/node/browser/DocumentFolderBrowserFragment.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/workflow/task/TaskFilterExpandableAdapter.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/ui/form/BaseField.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/ui/form/TextField.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/ui/form/views/AlfrescoFieldView.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/ui/form/views/EditTextFieldView.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/widgets/ActionShortcutActivity.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/widgets/BaseShortcutActivity.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/widgets/FolderShortcutActivity.java
alfresco-mobile-android/src/main/res/values/strings.xml
platform/foundation/src/main/java/org/alfresco/mobile/android/api/services/impl/LocalConfigServiceImpl.java
platform/foundation/src/main/res/layout/app_webview.xml

MOBILE-3200
Update embedded configuration.

MOBILE-3202

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/activity/MainActivity.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/activity/WelcomeActivity.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/menu/MainMenuFragment.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/operation/OperationsFragment.java

Move Notifications menu to HomeScreen Overflow menu

Add About screen as option menu in Welcome Screen

---

alfresco-mobile-android/src/main/res/values/ids.xml
alfresco-mobile-android/src/main/res/xml/app_restrictions.xml

Update Restrictions Keys

---

alfresco-mobile-android/build.gradle
alfresco-mobile-android/src/debug/java/org/alfresco/mobile/android/application/managers/DevToolsManagerImpl.java
alfresco-mobile-android/src/debug/res/values/keys.xml
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/preferences/AccountSettingsFragment.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/preferences/GeneralPreferences.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/managers/extensions/AnalyticHelper.java
alfresco-mobile-android/src/main/res/layout/fr_settings.xml
alfresco-mobile-android/src/main/res/values/keys.xml
extensions/analytics/src/main/java/org/alfresco/mobile/android/application/extension/analytics/GAnalyticsManagerImpl.java
platform/foundation/src/main/java/org/alfresco/mobile/android/api/model/config/impl/ConfigurationImpl.java
platform/foundation/src/main/java/org/alfresco/mobile/android/api/services/impl/AbstractConfigServiceImpl.java
platform/foundation/src/main/java/org/alfresco/mobile/android/api/services/impl/LocalConfigServiceImpl.java
platform/foundation/src/main/java/org/alfresco/mobile/android/platform/extensions/AnalyticsHelper.java
platform/foundation/src/main/java/org/alfresco/mobile/android/platform/extensions/AnalyticsManager.java
platform/foundation/src/main/java/org/alfresco/mobile/android/platform/extensions/DevToolsManager.java
platform/foundation/src/main/res/layout/row_two_lines_checkbox.xml

ANDROID-245
ANDROID-235
ANDROID-233
ANDROID-241

Sprint 1 - 2

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/managers/ActionUtils.java
alfresco-mobile-android/src/main/res/values/strings.xml

ANDROID-238

---

alfresco-mobile-android/src/main/assets/Configuration/embedded_config.json
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/activity/MainActivity.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/configuration/features/AbstractConfigFeature.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/configuration/features/ConfigFeatureHelper.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/configuration/features/DataProtectionConfigFeature.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/configuration/features/PasscodeConfigFeature.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/configuration/features/SyncCellularConfigFeature.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/preferences/AccountSettingsFragment.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/preferences/GeneralPreferences.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/preferences/PasscodePreferences.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/security/PassCodeActivity.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/security/PassCodeDialogFragment.java
alfresco-mobile-android/src/main/res/layout/app_passcode_simple.xml
alfresco-mobile-android/src/main/res/values/strings.xml
platform/foundation/src/main/java/org/alfresco/mobile/android/api/model/config/FeatureConfig.java
platform/foundation/src/main/java/org/alfresco/mobile/android/platform/extensions/AnalyticsHelper.java
platform/foundation/src/main/java/org/alfresco/mobile/android/platform/extensions/AnalyticsManager.java
platform/foundation/src/main/java/org/alfresco/mobile/android/ui/activity/AlfrescoActivity.java

ANDROID-309
ANDROID-310
ANDROID-296

ANDROID-271

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/activity/MainActivity.java
platform/foundation/src/main/java/org/alfresco/mobile/android/platform/extensions/AnalyticsManager.java
platform/foundation/src/main/java/org/alfresco/mobile/android/sync/SyncContentManager.java

ANDROID-56

---

alfresco-mobile-android/src/main/assets/Configuration/Messages/en_embedded_strings.properties
alfresco-mobile-android/src/main/res/values/strings.xml
extensions/scansnap/src/main/res/values/scansnap_strings.xml
platform/foundation/src/main/res/values/alfresco_strings.xml

1.8 rebranding

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/preferences/AccountSettingsFragment.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/preferences/PasscodePreferences.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/signin/AccountServerFragment.java
alfresco-mobile-android/src/main/res/layout/fr_account_server.xml
alfresco-mobile-android/src/main/res/values-de/strings.xml
alfresco-mobile-android/src/main/res/values-es/strings.xml
alfresco-mobile-android/src/main/res/values-fr/strings.xml
alfresco-mobile-android/src/main/res/values-it/strings.xml
alfresco-mobile-android/src/main/res/values-ja/strings.xml
alfresco-mobile-android/src/main/res/values-zh-rCN/strings.xml
alfresco-mobile-android/src/main/res/values/strings.xml

ANDROID-396
ANDROID-397
ANDROID-398
ANDROID-399
ANDROID-400
ANDROID-401

Localisation improvements

---

alfresco-mobile-android/src/main/res/values-de/strings.xml
alfresco-mobile-android/src/main/res/values-es/strings.xml
alfresco-mobile-android/src/main/res/values-fr/strings.xml
alfresco-mobile-android/src/main/res/values-it/strings.xml
alfresco-mobile-android/src/main/res/values-ja/strings.xml
alfresco-mobile-android/src/main/res/values-zh-rCN/strings.xml

Fix Locale

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/node/browser/DocumentFolderBrowserFragment.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/managers/SyncContentManagerImpl.java

Story https://issues.alfresco.com/jira/browse/ANDROID-175

ANDROID-175 Provide sync warning when a sync selection is over 20MB on cellular

---

alfresco-mobile-android/build.gradle

Incremented code version from 80 to 81

Code version 81

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/sync/ResolveConflictSyncDialogFragment.java

Issue available at https://issues.alfresco.com/jira/browse/ANDROID-567

ANDROID-567 Synced Content conflict saves file to wrong location

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/providers/storage/StorageAccessDocumentsProvider.java
platform/foundation/src/main/java/org/alfresco/mobile/android/async/account/CreateAccountOperation.java

Link to story https://issues.alfresco.com/jira/browse/ANDROID-573

ANDROID-573 Content app doesn't appear in the document provider list

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/providers/storage/StorageAccessDocumentsProvider.java

Story https://issues.alfresco.com/jira/browse/ANDROID-572

ANDROID-572 Support SAML in Android Document Provider

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/providers/storage/StorageAccessDocumentsProvider.java

Story available at https://issues.alfresco.com/jira/browse/ANDROID-582

ANDROID-582 Crash on attempt to open Site after attempt to update file in offline mode using Word

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/providers/storage/StorageAccessDocumentsProvider.java

Added the acceptance criteria of telling the user to login again inside the application when the session expires
Link to the story https://issues.alfresco.com/jira/browse/ANDROID-572

ANDROID-572 Support SAML auth in Android Document Provider

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/providers/storage/StorageAccessDocumentsProvider.java

Story https://issues.alfresco.com/jira/browse/ANDROID-572

ANDROID-572 added another check for stale session

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/providers/storage/StorageAccessDocumentsProvider.java

Story https://issues.alfresco.com/jira/browse/ANDROID-572

ANDROID-572 added a fix for when the app is closed and the account is SAML type

---

alfresco-mobile-android/build.gradle

Updated minimum SDK version to Kitkat 19
Story https://issues.alfresco.com/jira/browse/ANDROID-585

ANDROID-585 Update Minimum Android version to 4.4

---

platform/foundation/src/main/res/values/alfresco_strings.xml

Story available at https://issues.alfresco.com/jira/browse/ANDROID-589

ANDROID-589 Update the UI string re: ANDROID-572

---

alfresco-mobile-android/src/main/res/values/strings.xml

Story available at https://issues.alfresco.com/jira/browse/ANDROID-591

ANDROID-591 Update the UI text in the About screen

---

alfresco-mobile-android/src/main/res/values-de/strings.xml
alfresco-mobile-android/src/main/res/values-es/strings.xml
alfresco-mobile-android/src/main/res/values-fr/strings.xml
alfresco-mobile-android/src/main/res/values-it/strings.xml
alfresco-mobile-android/src/main/res/values-ja/strings.xml
alfresco-mobile-android/src/main/res/values-zh-rCN/strings.xml
platform/foundation/src/main/res/values-de/alfresco_strings.xml
platform/foundation/src/main/res/values-es/alfresco_strings.xml
platform/foundation/src/main/res/values-fr/alfresco_strings.xml
platform/foundation/src/main/res/values-it/alfresco_strings.xml
platform/foundation/src/main/res/values-ja/alfresco_strings.xml
platform/foundation/src/main/res/values-zh-rCN/alfresco_strings.xml

Story available at https://issues.alfresco.com/jira/browse/ANDROID-578

ANDROID-578 Added localization for the unlocalized strings

---

alfresco-mobile-android/build.gradle
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/VersionNumber.java
gradle.properties
platform/foundation/src/main/java/org/alfresco/mobile/android/sync/SyncContentProvider.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-618

ANDROID-618 SQL Injection Vulnerability

---

alfresco-mobile-android/build.gradle

JIRA https://issues.alfresco.com/jira/browse/ANDROID-633

ANDROID-633 Update target API version

---

platform/foundation/src/main/java/org/alfresco/mobile/android/platform/exception/AlfrescoExceptionHelper.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-635

ANDROID-635 Not relevant error message on attempt to rename record files

---

platform/foundation/src/main/java/org/alfresco/mobile/android/sync/SyncContentProvider.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-636

ANDROID-636 SQL Injection Vulnerability 2

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/node/browser/DocumentFolderBrowserFragment.java
platform/foundation/src/main/java/org/alfresco/mobile/android/async/node/sync/SyncNodeOperation.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-632

ANDROID-632 Crash on delete file from folder sync in progress

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/workflow/CreateTaskFragment.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-641

ANDROID-641 Crash on attempt to create a task with 2 attachments

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/node/browser/DocumentFolderBrowserFragment.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-645

ANDROID-645 Multiple selection not working for short taps on mobile phones

---

alfresco-mobile-android/src/main/AndroidManifest.xml
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/create/DocumentPropertiesDialogFragment.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/create/EditorsDialogFragment.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/managers/ActionUtils.java
alfresco-mobile-android/src/main/res/xml/provider_paths.xml
platform/foundation/build.gradle
platform/foundation/src/main/java/org/alfresco/mobile/android/platform/intent/BaseActionUtils.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-644

ANDROID-644 Google Play Console - FileUriExposedException

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/editors/text/TextEditorActivity.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-647

ANDROID-647 Size limit on text editor

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/create/DocumentPropertiesDialogFragment.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/managers/ActionUtils.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-649

ANDROID-649 Crash on attempt to create a new file with app editor, ANDROID 7

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/actions/NodeActions.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/actions/NodeIdActions.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-637

ANDROID-637 Both Sync and Unsync available on Sync drop-down

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/node/details/NodeDetailsFragment.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/node/download/DownloadDialogFragment.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/node/download/DownloadDocumentHolder.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/node/rendition/PreviewFragment.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-650

ANDROID-650 Crash on attempt to open an fresh uploaded image

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/capture/PhotoCapture.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/capture/VideoCapture.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-651

ANDROID-651 Record video /audio are not working

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/editors/text/TextEditorActivity.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-648

ANDROID-648 ANR- Application not responding on apply encodings on large txt files

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/managers/ActionUtils.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-653

ANDROID-653 Crash on attempt to open synced file that have been declared as record.

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/capture/AudioCapture.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-652

ANDROID-652 Audio file not saved even the option appear on phone (android 7)

---

alfresco-mobile-android/build.gradle
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/activity/MainActivity.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/activity/MainActivityHelper.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/node/download/DownloadDialogFragment.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-656

ANDROID-656 User moved out from app on tap back from image/video view

---

platform/foundation/src/main/java/org/alfresco/mobile/android/sync/operations/SyncContentDownload.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-655

ANDROID-655 Synced records cannot be opened neither from Sites, neither from Synced content

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/managers/ActionUtils.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-661

ANDROID-661 Not able to open images or videos from Downloads

---

alfresco-mobile-android/src/debug/java/org/alfresco/mobile/android/application/fragments/config/ConfigMenuEditorFragment.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/configuration/model/ConfigModelHelper.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-663

ANDROID-663 Crash on Menu editor on attempt to save something or tap on Settings

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/VersionNumber.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/editors/text/TextEditorActivity.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/managers/ActionUtils.java
gradle.properties
platform/foundation/src/main/java/org/alfresco/mobile/android/async/file/FileOperationRequest.java
platform/foundation/src/main/java/org/alfresco/mobile/android/async/file/open/OpenFileOperation.java
platform/foundation/src/main/java/org/alfresco/mobile/android/async/file/open/OpenFileRequest.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-660

ANDROID-660 Crash on attempt to open files with alfresco editor from Downloads

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/editors/text/TextEditorActivity.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-669

ANDROID-669 Empty content or error message on changing encoding

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/site/request/JoinSiteRequestAdapter.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/site/request/JoinSiteViewHolder.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-386

ANDROID-386 Cannot cancel request to join sites

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/workflow/process/ProcessTasksAdapter.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/workflow/process/ProcessViewHolder.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-598

ANDROID-598 No task history displayed

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/editors/text/TextEditorActivity.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-676

ANDROID-676 Save button enabled in Alfresco editor, even no change is made

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/menu/MainMenuFragment.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-674

ANDROID-674 Account name displayed correctly on update only using back as navigation.

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/sync/ResolveConflictSyncDialogFragment.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-677

ANDROID-677 Conflict generated for synced file after we start review and we edit the file

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/activity/MainActivity.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/activity/MainActivityHelper.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/capture/DeviceCaptureHelper.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/fileexplorer/FileExplorerFragment.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/node/browser/DocumentFolderBrowserFragment.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-682

ANDROID-682 java.lang.RuntimeException in MainActivityHelper

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/capture/AudioCapture.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/capture/DeviceCapture.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/capture/DeviceCaptureHelper.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/capture/PhotoCapture.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/capture/VideoCapture.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/fileexplorer/FileExplorerFragment.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/node/browser/DocumentFolderBrowserFragment.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-683

ANDROID-683 Files saved in wrong locations

---

platform/foundation/build.gradle

JIRA https://issues.alfresco.com/jira/browse/ANDROID-673

ANDROID-673 Username instead of email address

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/activity/MainActivity.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-658

ANDROID-658 Notification to about my.alfresco.com shutting down

---

alfresco-mobile-android/src/main/res/values/strings.xml

Notification to about my.alfresco.com shutting down

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/configuration/ConfigurableActionHelper.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/config/MenuConfigFragment.java
platform/foundation/src/main/java/org/alfresco/mobile/android/api/model/config/ConfigConstants.java
platform/foundation/src/main/java/org/alfresco/mobile/android/async/favorite/CleanFavoritesEvent.java
platform/foundation/src/main/java/org/alfresco/mobile/android/async/favorite/CleanFavoritesOperation.java
platform/foundation/src/main/java/org/alfresco/mobile/android/async/favorite/CleanFavoritesRequest.java
platform/foundation/src/main/java/org/alfresco/mobile/android/async/local/CleanLocalFilesEvent.java
platform/foundation/src/main/java/org/alfresco/mobile/android/async/local/CleanLocalFilesOperation.java
platform/foundation/src/main/java/org/alfresco/mobile/android/async/local/CleanLocalFilesRequest.java
platform/foundation/src/main/java/org/alfresco/mobile/android/platform/favorite/FavoritesManager.java
platform/foundation/src/main/java/org/alfresco/mobile/android/platform/io/AlfrescoStorageManager.java
platform/foundation/src/main/res/values/config_default_async_operations.xml

JIRA https://issues.alfresco.com/jira/browse/ANDROID-672

ANDROID-672 Options available even the tabs are hidden from menu

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/activity/MainActivity.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/signin/AccountOAuthFragment.java
alfresco-mobile-android/src/main/res/values/strings.xml

JIRA https://issues.alfresco.com/jira/browse/ANDROID-687

ANDROID-687 Update my.alfresco.com decommission notification text

---

alfresco-mobile-android/src/main/res/values-de/strings.xml
alfresco-mobile-android/src/main/res/values-es/strings.xml
alfresco-mobile-android/src/main/res/values-fr/strings.xml
alfresco-mobile-android/src/main/res/values-it/strings.xml
alfresco-mobile-android/src/main/res/values-ja/strings.xml
alfresco-mobile-android/src/main/res/values-zh-rCN/strings.xml

JIRA https://issues.alfresco.com/jira/browse/ANDROID-686

ANDROID-686 ACS 1.8.5 Localisation

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/activity/MainActivity.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/signin/AccountOAuthFragment.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-688

ANDROID-688 Disable my.alfresco.com notification until a proper shutdown date is picked

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/workflow/CreateTaskFragment.java

More info can be found at:
https://issues.alfresco.com/jira/browse/ANDROID-704

ANDROID-704 App crashes when trying to start a workflow

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/activity/MainActivity.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/signin/AccountOAuthFragment.java
alfresco-mobile-android/src/main/res/values/strings.xml

JIRA https://issues.alfresco.com/jira/browse/ANDROID-706

ANDROID-706 Enable my.alfresco.com notification

---

alfresco-mobile-android/src/main/res/values-de/strings.xml
alfresco-mobile-android/src/main/res/values-es/strings.xml
alfresco-mobile-android/src/main/res/values-fr/strings.xml
alfresco-mobile-android/src/main/res/values-it/strings.xml
alfresco-mobile-android/src/main/res/values-ja/strings.xml
alfresco-mobile-android/src/main/res/values-zh-rCN/strings.xml

JIRA https://issues.alfresco.com/jira/browse/ANDROID-707

ANDROID-707 Localization of the text notification

---

alfresco-mobile-android/build.gradle
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/signin/AccountServerFragment.java
alfresco-mobile-android/src/main/res/layout/fr_account_server.xml
gradle.properties
platform/foundation/src/main/res/values/alfresco_strings.xml

JIRA https://issues.alfresco.com/jira/browse/ANDROID-711

ANDROID-711 [MNT] Alfresco Android App Gives Server validation message

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/activity/MainActivity.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-724

ANDROID-724 [ACS] The application is crashing when re-opening the application after deleting the account

---

platform/foundation/src/main/res/values-de/alfresco_strings.xml
platform/foundation/src/main/res/values-es/alfresco_strings.xml
platform/foundation/src/main/res/values-fr/alfresco_strings.xml
platform/foundation/src/main/res/values-it/alfresco_strings.xml
platform/foundation/src/main/res/values-ja/alfresco_strings.xml
platform/foundation/src/main/res/values-zh-rCN/alfresco_strings.xml

JIRA https://issues.alfresco.com/jira/browse/ANDROID-723

ANDROID-723 ANDROID 1.8.6 Localisations

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/node/download/DownloadDialogFragment.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/managers/ActionUtils.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-735

ANDROID-735 'Decryption Failed' when sharing a document as attachment

---

platform/foundation/src/main/java/org/alfresco/mobile/android/platform/EventBusManager.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-739

Application is crashing when starting it

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/providers/search/HistorySearchProvider.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-779

ANDROID-779 Fix SQL injection vulnerability exposed in veracode report

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/node/details/NodeDetailsFragment.java

JIRA https://issues.alfresco.com/jira/browse/ANDROID-730

ANDROID-730 Fix Document Previews

---

alfresco-mobile-android/build.gradle
gradle.properties

JIRA https://issues.alfresco.com/jira/browse/ANDROID-859

ANDROID-859 Update ACS Android Target

---

alfresco-mobile-android/build.gradle
alfresco-mobile-android/src/main/AndroidManifest.xml
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/AlfrescoApplication.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/activity/BannerActivity.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/activity/MainActivity.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/activity/PublicDispatcherActivity.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/node/browser/DocumentFolderBrowserFragment.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/fragments/node/upload/UploadFormFragment.java
alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/widgets/DocumentFolderPickerFragment.java
alfresco-mobile-android/src/main/res/drawable/ic_banner_logo.xml
alfresco-mobile-android/src/main/res/layout/activity_banner.xml
alfresco-mobile-android/src/main/res/values/layout.xml
alfresco-mobile-android/src/main/res/values/strings.xml
build.gradle
extensions/analytics/build.gradle
extensions/analytics/src/main/AndroidManifest.xml
gradle/wrapper/gradle-wrapper.properties
platform/foundation/src/main/res/values/dimens.xml

Mobileapps-1124

---

alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/activity/BannerActivity.java
alfresco-mobile-android/src/main/res/values-de/strings.xml
alfresco-mobile-android/src/main/res/values-es/strings.xml
alfresco-mobile-android/src/main/res/values-fr/strings.xml
alfresco-mobile-android/src/main/res/values-it/strings.xml
alfresco-mobile-android/src/main/res/values-ja/strings.xml
alfresco-mobile-android/src/main/res/values-zh-rCN/strings.xml

localization_banner
